export const APP_STRINGS = {
  COMMON: {
    CANCEL: 'Cancelar',
    DELETE: 'Eliminar',
    OK: 'Aceptar',
    ERROR: 'Error',
    SUCCESS: 'Éxito',
    SAVE: 'Guardar',
    SAVE_CHANGES: 'Guardar cambios',
  },
  ERROR: {
    LOGIN_FAILED: 'Error al iniciar sesión',
    SIGNUP_FAILED: 'Error al registrarse',
    PASSWORD_CHANGE_FAILED: 'No se pudo cambiar la contraseña',
    VERIFICATION_FAILED: 'Código de verificación inválido',
    RESEND_FAILED: 'Error al reenviar el código',
    EMAIL_FAILED: 'Error al enviar el correo',
  },
  PROFILE: {
    TITLE: 'Mi perfil',
    PERSONAL_INFO: 'Información personal',
    CHANGE_PASSWORD: 'Cambiar contraseña',
    MY_ADDRESSES: 'Mis direcciones',
    DANGER_ZONE: 'Zona de riesgo',
    LOGOUT: 'Cerrar sesión',
    DELETE_ACCOUNT: 'Eliminar cuenta',
    LOGOUT_CONFIRM_TITLE: 'Cerrar sesión',
    LOGOUT_CONFIRM_MSG: '¿Seguro que deseas cerrar sesión?',
    DELETE_ACCOUNT_CONFIRM_TITLE: 'Eliminar cuenta',
    DELETE_ACCOUNT_CONFIRM_MSG:
      '¿Seguro que deseas eliminar tu cuenta? Esta acción no se puede deshacer.',
    UPDATE_SUCCESS: 'Perfil actualizado correctamente',
    UPDATE_ERROR: 'Error al actualizar el perfil',
    DELETE_ERROR: 'No se pudo eliminar la cuenta',
    SAVE_CHANGES: 'Guardar cambios',
    USERNAME: 'Usuario',
    FULL_NAME: 'Nombre completo',
    NAME: 'Nombre',
    EMAIL: 'Correo electrónico',
    EMAIL_PLACEHOLDER: 'usuario@ejemplo.com',
    EDIT: 'Editar perfil',
    BIO: 'Biografía',
    PASSWORD: {
      CURRENT: 'Contraseña actual',
      NEW: 'Nueva contraseña',
      CONFIRM: 'Confirmar contraseña',
    },
    STATS: {
      POSTS: 'Publicaciones',
      PHOTOS: 'Fotos',
      VIDEOS: 'Videos',
    },
    ABOUT_TITLE: 'Acerca de mí',
    EMPTY_POSTS: '📝 Tus posts aparecerán aquí',
    EMPTY_POSTS_DESC: 'Comparte tus experiencias y aventuras con la comunidad',
    EMPTY_PHOTOS: '📸 Tus fotos aparecerán aquí',
    EMPTY_PHOTOS_DESC: 'Todas tus capturas memorables en un solo lugar',
    EMPTY_VIDEOS: '🎥 Tus videos aparecerán aquí',
    EMPTY_VIDEOS_DESC: 'Revive tus mejores momentos en video',
  },
  COUPONS: {
    TITLE: 'Mis cupones',
    ACTIVE_COUNT: (count: number) => `${count} cupón${count !== 1 ? 'es' : ''}`,
    APPLY_TITLE: 'Aplicar cupón',
    APPLY_MSG: (code: string, discountStr: string, minPurchaseStr: string) =>
      `¿Quieres aplicar el cupón "${code}"?\n\nDescuento: ${discountStr}\n${minPurchaseStr}`,
    APPLY_BTN: 'Aplicar',
    SUCCESS_MSG: (code: string) => `El cupón "${code}" se ha aplicado a tu carrito!`,
    TABS: {
      ALL: 'Todos',
      ACTIVE: 'Activos',
      EXPIRED: 'Caducados',
      USED: 'Usados',
    },
    EMPTY_STATE: {
      TITLE: 'No se encontraron cupones',
      NO_ACTIVE: 'No tienes cupones activos por el momento',
      NO_EXPIRED: 'No hay cupones caducados',
      NO_USED: 'No hay cupones usados',
      START_ORDERING: 'Comienza a ordenar para recibir cupones exclusivos',
    },
  },
  FAVORITES: {
    TITLE: 'Favoritos',
    ITEMS_SAVED: (count: number) => `${count} elemento${count !== 1 ? 's' : ''}`,
    CLEAR_ALL_TITLE: 'Eliminar todos los favoritos',
    CLEAR_ALL_MSG: (count: number) =>
      `¿Eliminar los ${count} elemento${count > 1 ? 's' : ''} de favoritos?`,
    CLEAR_ALL_BTN: 'Eliminar todos',
    CLEAR_SUCCESS: '¡Todos los favoritos eliminados!',
    EMPTY_TITLE: 'Aún no hay favoritos',
    EMPTY_DESC:
      'Toca el icono de corazón en tus platos favoritos para guardarlos aquí y acceder rápidamente más tarde.',
    EXPLORE_MENU: 'Explorar menú',
  },
  NOTIFICATIONS: {
    TITLE: 'Notificaciones',
    UNREAD_COUNT: (count: number) => `${count} sin leer`,
    ALL_CAUGHT_UP: 'No hay notificaciones nuevas',
    MARK_ALL_READ: 'Marcar todo como leído',
    GROUPS: {
      TODAY: 'Hoy',
      YESTERDAY: 'Ayer',
      OLDER: 'Anteriores',
    },
  },
  AUTH: {
    LOGIN_TITLE: 'Bienvenido',
    LOGIN_SUBTITLE: 'Inicia sesión para continuar',
    REMEMBER_ME: 'Recordarme',
    SIGNING_IN: 'Iniciando sesión...',
    OR_WITH: 'o continúa con',
    NEXT: 'Siguiente',
    FIRST_NAME_LABEL: 'Nombre',
    LAST_NAME_LABEL: 'Apellido',
    FIRST_NAME_PLACEHOLDER: 'Tu nombre',
    LAST_NAME_PLACEHOLDER: 'Tu apellido',
    CREATING_ACCOUNT: 'Creando cuenta...',
    COMPLETE_REGISTRATION: 'Completa tu registro',
    EMAIL_LABEL: 'Correo electrónico',
    PASSWORD_LABEL: 'Contraseña',
    FORGOT_PASSWORD: '¿Olvidaste tu contraseña?',
    LOGIN_BTN: 'Iniciar sesión',
    NO_ACCOUNT: '¿No tienes una cuenta?',
    SIGNUP_LINK: 'Regístrate',
    SIGNUP_TITLE: 'Registro',
    USERNAME_LABEL: 'Usuario',
    USERNAME_PLACEHOLDER: 'Tu usuario',
    EMAIL_PLACEHOLDER: 'tu@correo.com',
    PASSWORD_PLACEHOLDER: 'Tu contraseña',
    CONFIRM_PASSWORD_LABEL: 'Repetir contraseña',
    CONFIRM_PASSWORD_PLACEHOLDER: 'Repite la contraseña',
    SIGNUP_BTN: 'Registrarse',
    HAVE_ACCOUNT_LOGIN: '¿Ya tienes una cuenta? Inicia sesión',
    ALREADY_HAVE_ACCOUNT: '¿Ya tienes cuenta?',
    LOGIN_LINK: 'Iniciar sesión',
    SEND_CODE_TITLE: 'Recuperar contraseña',
    SEND_CODE_SUBTITLE: 'Introduce tu correo para recibir un código',
    SEND_CODE_BTN: 'Enviar código',
    RECOVER_PASSWORD_TITLE: 'Recupera tu contraseña',
    VERIFY_EMAIL_TITLE: 'Verifica tu correo',
    VERIFY_CODE_TITLE: 'Verificar código',
    VERIFY_CODE_HEADING: 'Introduce tu código de verificación',
    VERIFY_CODE_SUBTITLE: 'Ingresa el código enviado a tu correo',
    VERIFY_CODE_BTN: 'Verificar',
    SEND_BTN: 'Enviar',
    BACK_TO_LOGIN: 'Volver al inicio de sesión',
    CODE_LABEL: 'Código de verificación',
    CODE_PLACEHOLDER: 'Ingresa el código',
    RESEND_CODE: 'Reenviar código',
    CHANGE_PASSWORD_TITLE: 'Nueva contraseña',
    CHANGE_PASSWORD_SUBTITLE: 'Introduce tu nueva contraseña',
    CHANGE_PASSWORD_BTN: 'Cambiar contraseña',
    NEW_PASSWORD_LABEL: 'Nueva contraseña',
    NEW_PASSWORD_PLACEHOLDER: 'Tu nueva contraseña',
    CONFIRM_NEW_PASSWORD_LABEL: 'Confirmar contraseña',
    CONFIRM_NEW_PASSWORD_PLACEHOLDER: 'Confirma tu contraseña',
  },
  VALIDATION: {
    MIN_LENGTH_8: 'Mínimo 8 caracteres',
    MIN_LENGTH_6: 'Mínimo 6 caracteres',
    PASSWORD_MIN_8: 'La contraseña debe tener al menos 8 caracteres',
    PASSWORD_COMPLEXITY: 'Debe incluir mayúsculas, minúsculas, número y carácter especial.',
    PASSWORDS_NOT_MATCH: 'Las contraseñas no coinciden',
    REQUIRED_FIELD: 'Este campo es obligatorio.',
    REQUIRED_USERNAME: 'El usuario es obligatorio',
    PATTERN_USERNAME: 'El usuario puede contener letras, números, guion bajo o guion',
    REQUIRED_NAME: 'El nombre es obligatorio',
    REQUIRED_EMAIL: 'El correo es obligatorio',
    REQUIRED_PASSWORD: 'La contraseña es obligatoria',
    REQUIRED_CONFIRM_PASSWORD: 'Por favor confirma tu contraseña',
    REQUIRED_VERIFICATION_CODE: 'El código de verificación es obligatorio',
    CODE_LENGTH_6: 'El código debe tener 6 dígitos',
    CODE_INVALID_FORMAT: 'Por favor ingresa un código válido de 6 dígitos',
    INVALID_EMAIL: 'Correo electrónico inválido',
  },
  INPUT: {
    ACCESSIBILITY_HINT: 'Introduce tu',
    TOGGLE_PASSWORD: 'Alternar visibilidad de la contraseña',
    TOGGLE_PASSWORD_HINT: 'Presiona para mostrar u ocultar la contraseña',
  },
  NAVIGATION: {
    TAB_HOME: 'Inicio',
    TAB_MENU: 'Menú',
    TAB_MAP: 'Mapa',
    TAB_ORDERS: 'Pedidos',
    DRAWER_TITLE: 'Feed',
    HEADER_NOTIFICATIONS: 'Notificaciones',
    HEADER_CART: 'Carrito',
    MAP_SEARCH_PLACEHOLDER: 'Buscar en el mapa',
    SEARCH: 'Buscar',
    FILTER: 'Filtrar',
  },
  DRAWER: {
    SETTINGS_TITLE: 'Ajustes',
    PROFILE: 'Perfil',
    PAYMENT_METHOD: 'Método de pago',
    LANGUAGE: 'Idioma',
    DARK_MODE: 'Modo oscuro',
    FEATURES_TITLE: 'Funciones',
    FAVORITES: 'Favoritos',
    COUPONS: 'Cupones',
    INFO_TITLE: 'Información',
    ABOUT_US: 'Sobre nosotros',
    HELP: 'Ayuda',
    DEMO_USER: 'Usuario demo',
    DEMO_ROLE: 'Miembro',
    LOGOUT: 'Cerrar sesión',
    VERSION: 'Versión 1.0.0',
    DEMO_INITIALS: 'NE',
  },
  LANG: {
    ENGLISH: 'Inglés',
    SPANISH: 'Español',
  },
  CAMERA: {
    NEED_PERMISSION: 'Necesitamos permiso para usar la cámara',
    GRANT_PERMISSION: 'Conceder permiso',
    HINT: 'Apunta la cámara al objetivo',
  },
  HOME: {
    TABS: {
      DINNERS: 'Cenas',
      DRINKS: 'Bebidas',
      BREAKFASTS: 'Desayunos',
      SNACKS: 'Aperitivos',
      DESSERTS: 'Postres',
    },
    MAP: {
      RESTAURANT_1_TITLE: 'Restaurante Central',
      RESTAURANT_1_DESC: 'Av. Principal 123, Centro',
      RESTAURANT_2_TITLE: 'Restaurante Oeste',
      RESTAURANT_2_DESC: 'Calle 456, Oeste',
      LOADING_LOCATION: 'Obteniendo ubicación...',
      LOCATION_ERROR: 'No se pudo cargar el mapa.',
      LOCATION_ERROR_DESC: 'Por favor revisa los permisos de ubicación',
      RETRY_BTN: 'Reintentar',
      MY_LOCATION: 'Mi ubicación',
      YOU_ARE_HERE: 'Estás aquí',
      ADD_LOCATION_TITLE: 'Agregar ubicación',
      ADD_LOCATION_DESC: 'Guardar una nueva dirección de entrega',
      ADD_LOCATION_BTN: 'Agregar esta ubicación',
    },
    MENU: {
      TITLE: 'Menú',
    },
    NAV: {
      PLACES: 'Lugares',
      HOTELS: 'Hoteles',
      RESTAURANTS: 'Restaurantes',
      BEACHES: 'Playas',
      TRANSPORTS: 'Transportes',
    },
    FEED: {
      TITLE: 'Explora',
      SUBTITLE: 'Descubre lugares, hoteles y restaurantes cerca de ti',
      EMPTY_TITLE: 'Aún no hay contenido',
      EMPTY_DESC: 'Tus publicaciones o lugares guardados aparecerán aquí',
    },
    ORDERS: {
      TITLE: 'Pedidos',
    },
  },
  ADDRESSES: {
    LIST: {
      TITLE: 'Mis direcciones',
      SUBTITLE: 'Direcciones principales de entrega',
      CREATE_BTN: 'Crear nueva dirección',
    },
    MAP: {
      TITLE: 'Localizar dirección',
      SEARCH_PLACEHOLDER: 'Introduce tu dirección o punto de referencia',
      SEARCHING: 'Buscando...',
      NO_RESULTS: 'No se encontraron resultados',
      CONFIRM_BTN: 'Confirmar ubicación',
      STREET: 'Calle',
      CITY: 'Ciudad',
      DETAILS: 'Detalles adicionales',
      SAVE_BTN: 'Guardar ubicación',
      EDIT_TITLE: 'Editar ubicación',
      LOADING: 'Cargando mapa...',
      ERROR_TITLE: 'No se pudo cargar el mapa',
      ERROR_DESC: 'Por favor habilita los permisos de ubicación',
      RETRY_BTN: 'Reintentar',
      CONFIRM_TITLE: 'Confirma tu dirección',
    },
  },
  INFO: {
    ABOUT: {
      HERO_TITLE: 'Nic-Explore — Turismo sostenible, cultura y tecnología',
      HIGHLIGHTS_TITLE: '¿Qué hace única a nuestra plataforma?',
      TEAM_TITLE: 'Equipo detrás de la experiencia',
    },
    HELP: {
      TITLE: 'Centro de ayuda y soporte',
      DESC: 'Consulta guías, reporta identificaciones o solicita asistencia; nuestro equipo y la comunidad están para ayudarte.',
      CHANNELS_TITLE: 'Canales de soporte',
      QUICK_STEPS_TITLE: 'Pasos rápidos de solución',
      FAQ_TITLE: 'Preguntas frecuentes',
      SUPPORT_CHANNELS: [
        {
          title: 'Chat en la app',
          description:
            'Conéctate con nuestro equipo para resolver dudas sobre la app, reportar identificaciones o problemas técnicos.',
          availability: 'Disponible Lunes a Sábado · 9:00 a 18:00 (hora local)',
        },
        {
          title: 'Correo de soporte',
          description:
            'Escríbenos a soporte@nic-explore.app para preguntas detalladas o consultas sobre colaboraciones y alianzas.',
          availability: 'Tiempo de respuesta medio: 24 horas hábiles',
        },
        {
          title: 'Línea telefónica',
          description:
            'Llama al número de soporte para consultas urgentes o asistencia en campo (según disponibilidad local).',
          availability: 'Soporte telefónico en horario de oficina',
        },
      ],
      QUICK_STEPS: [
        'Reinicia la app si experimentas problemas y verifica tu conexión.',
        'Comprueba las herramientas de diagnóstico en la pantalla principal.',
        'Si la identificación por IA falla, intenta tomar la foto con buena iluminación y desde diferentes ángulos.',
        'Reporta especies o sitios sospechosos desde la ficha de detalle para que nuestro equipo y la comunidad verifiquen.',
        'Verifica tus métodos de pago en Ajustes > Pagos antes de completar una reserva o compra.',
      ],
      FAQS: [
        {
          question: '¿Cómo funciona el reconocimiento por IA?',
          answer:
            'Toma una foto de un ave, planta o monumento desde la app; el sistema sugerirá coincidencias y mostrará información educativa y fuentes en segundos.',
        },
        {
          question: '¿Puedo reportar un error en la identificación?',
          answer:
            'Sí. Desde la ficha del elemento identificado puedes marcarlo como incorrecto y enviar evidencia; nuestro equipo y la comunidad revisarán la petición.',
        },
        {
          question: '¿Qué son los coleccionables digitales?',
          answer:
            'Los coleccionables son recompensas digitales que obtienes al identificar especies o visitar puntos de interés. Fomentan la exploración y pueden desbloquear logros.',
        },
      ],
    },
  },

  PAYMENT: {
    METHODS: {
      TITLE: 'Métodos de pago',
      SUBTITLE: 'Administra tus tarjetas guardadas',
      EMPTY_TITLE: 'No hay tarjetas guardadas',
      EMPTY_DESC: 'Agrega un método de pago para comenzar',
      DEFAULT_BADGE: 'Predeterminado',
      SET_DEFAULT: 'Establecer como predeterminado',
      REMOVE: 'Eliminar',
      REMOVE_TITLE: 'Eliminar tarjeta',
      REMOVE_DESC: (last4: string) => `¿Eliminar la tarjeta terminada en ${last4}?`,
      CANCEL: 'Cancelar',
      ADD_NEW_CARD: 'Agregar nueva tarjeta',
    },
    ADD_METHOD: {
      TITLE: 'Agregar nueva tarjeta',
      SUBTITLE: 'Los datos de tu tarjeta están encriptados y seguros',
      TAP_FLIP: 'Toca para voltear',
      CARD_HOLDER: 'TITULAR',
      YOUR_NAME: 'TU NOMBRE',
      VALID_THRU: 'VÁLIDO HASTA',
      CVV: 'CÓDIGO DE SEGURIDAD',
      INCOMPLETE_TITLE: 'Incompleto',
      INCOMPLETE_DESC: 'Por favor completa correctamente los datos de la tarjeta.',
      SUCCESS_TITLE: 'Tarjeta agregada',
      SUCCESS_DESC: (last4: string) => `La tarjeta terminada en ${last4} ha sido guardada.`,
      CARD_NUMBER_LABEL: 'Número de tarjeta',
      CARD_NUMBER_HINT: '1234 5678 9012 3456',
      CARD_HOLDER_LABEL: 'Nombre del titular',
      CARD_HOLDER_HINT: 'Juan Pérez',
      EXPIRY_LABEL: 'Fecha de vencimiento',
      EXPIRY_HINT: 'MM/AA',
      CVV_LABEL: 'CVV',
      CVV_HINT: '•••',
      ADD_CARD_BTN: 'Guardar tarjeta',
      ERRORS: {
        CARD_NUMBER_REQ: 'El número de tarjeta es obligatorio',
        CARD_NUMBER_INVALID: 'Debe tener 16 dígitos',
        HOLDER_REQ: 'El nombre del titular es obligatorio',
        HOLDER_INVALID: 'Ingresa un nombre válido (mín 3 caracteres)',
        EXPIRY_REQ: 'La fecha de vencimiento es obligatoria',
        EXPIRY_INVALID: 'Ingresa una fecha válida (MM/AA)',
        CVV_REQ: 'El CVV es obligatorio',
        CVV_INVALID: 'Debe tener al menos 3 dígitos',
        FORM_INCOMPLETE: 'Por favor completa todos los campos requeridos correctamente.',
      },
    },
    VERIFICATION: {
      TITLE: 'Pantalla de verificación',
    },
  },
  PRODUCT: {
    NOT_FOUND_TITLE: 'Producto no encontrado',
    NOT_FOUND_DESC: 'No pudimos cargar la información de este producto.',
    QUANTITY: 'Cantidad',
    ADD_BTN: 'Agregar',
    BEST_SELLER: 'Más vendido',
    PER_UNIT: 'por unidad',
    ACCESSIBILITY: {
      GO_BACK: 'Regresar',
      ADD_FAVORITE: 'Guardar en favoritos',
      REMOVE_FAVORITE: 'Eliminar de favoritos',
    },
  },
  NOT_FOUND: {
    TITLE: '¡Ups! Página no encontrada',
    DESCRIPTION:
      'La página que buscas puede haber sido eliminada, cambiado de nombre o estar temporalmente no disponible.',
    HOME_BTN: 'Inicio',
    BACK_BTN: 'Regresar',
  },
};

export const ROUTES = {
  HOME: '/AltaPinta',
  LOGIN: '/log-in',
  SIGNUP: '/sign-up',
  ADDRESSES: '/(drawer)/shared/addresses/list',
  SEND_EMAIL: '/send-email',
  SEND_CODE: '/send-code',
  CHANGE_PASSWORD: '/change-password',
  NOTIFICATIONS: '/features/notifications',
  CART: '/flows/checkout/cart',
  PROFILE_EDIT: '/flows/profile-management/edit-profile',
  PAYMENT_METHODS: '/settings/paymentMethod',
  ADD_PAYMENT_METHOD: '/settings/addPaymentMethods',
  FAVORITES: '/features/favorites',
  COUPONS: '/features/coupons',
  ABOUT_US: '/info/about-us',
  HELP: '/info/help',
  REVIEW: '/flows/checkout/review',
  MENU: '/menu',
  CONFIRMATION: '/flows/checkout/confirmation',
};

export const TIME_CONSTANTS = {
  MOCK_DELAY_MS: 1000,
};
